sudo: required

services:
  - docker

before_install:
  - docker build -t dadadev/pro-dev-flow-implementation -f Dockerfile.dev .

script:
  - docker run dadadev/pro-dev-flow-implementation npm run test -- --coverage